"""empty message

Revision ID: 20734e91cc15
Revises: 
Create Date: 2017-10-23 19:19:52.041023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20734e91cc15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squadron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aircrafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squardron_id', sa.Integer(), nullable=True),
    sa.Column('t_m_s', sa.String(length=64), nullable=True),
    sa.Column('airframe_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['squardron_id'], ['squadron.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usrename', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('squadron_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['squadron_id'], ['squadron.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('e_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mechanic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_m_s', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    op.drop_table('pilot')
    op.drop_table('mechanic')
    op.drop_table('engines')
    op.drop_table('user')
    op.drop_table('aircrafts')
    op.drop_table('squadron')
    # ### end Alembic commands ###
