"""empty message

Revision ID: 8c76f8806032
Revises: 
Create Date: 2017-10-28 19:22:30.851362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c76f8806032'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squadron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aircrafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_m_s', sa.String(length=64), nullable=True),
    sa.Column('squardron_id', sa.Integer(), nullable=True),
    sa.Column('airframe_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['squardron_id'], ['squadron.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usrename', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('squadron_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['squadron_id'], ['squadron.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('e_hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_due',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('type_inspection', sa.String(length=80), nullable=True),
    sa.Column('date_due', sa.Date(), nullable=True),
    sa.Column('hours_due', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'aircraft_id')
    )
    op.create_table('mechanic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.Column('aircraft_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_history',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('aircraft_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('type_inspection', sa.String(length=80), nullable=True),
    sa.Column('aircraft_hours', sa.Integer(), nullable=True),
    sa.Column('engine_hours', sa.Integer(), nullable=True),
    sa.Column('mechanic_id', sa.Integer(), nullable=True),
    sa.Column('date_complete', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircrafts.id'], ),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'aircraft_id', 'date_complete')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_history')
    op.drop_table('flights')
    op.drop_table('pilot')
    op.drop_table('mechanic')
    op.drop_table('maintenance_due')
    op.drop_table('engines')
    op.drop_table('user')
    op.drop_table('aircrafts')
    op.drop_table('squadron')
    # ### end Alembic commands ###
